name: S3 + Cloudfront deploy
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v1

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NEXT_PUBLIC_REWIRING_AMERICA_TOKEN: ${{ secrets.NEXT_PUBLIC_REWIRING_AMERICA_TOKEN }}
          envkey_NEXT_PUBLIC_REWIRING_AMERICA_API: ${{ secrets.NEXT_PUBLIC_REWIRING_AMERICA_API }}
          directory: <directory_name>
          file_name: .env
          fail_on_empty: false

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: / *